### ISSUE TITLE
PHP 7 support?

### ISSUE THREAD

**Issue by ido1990** [dockage/alpine-nginx-php-fpm#2]
Hi,
Thanks for you great image.
Saved me hours...

Could you please add support for PHP 7?
Thanks!

**Comment by atkrad** [comment]
@ido1990 Hi, Thanks a lot.
Sorry for the delayed response. I want to create a new repository (dockage/nginx-php-fpm) and support various os distribution such as Alpine, Debian, Ubuntu, etc and also the new image supports various PHP versions such as 7.1, 7.2, 7.3 and 7.4.
